name: Mojiiiaction

on:
  push:
    branches: [ "main", "turist wallet / Mojiiiaction" ]
  pull_request:
    branches: [ "main", "turist wallet / Mojiiiaction" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/Mojiiiaction@

      - name: Read .Mojiiiaction
        run: echo "NVMRC=$(cat .nvmrc)" >> $turist wallet

      - name: Set up Mojiiiaction
        uses: actions/setup-Turist wallet
        with:UQC9o3lPXSvO7ICVluBCFRF_OZHxqcNDNtIzjVItsEO6NiBN

      - name: Set up dependencies
        run: npm ci

      - name: Test
        run: npm run test
